- role: Program Sub-Chair
  link: https://ahli.cc/ml4h/
  organization: Machine Learning for Health Symposim (ML4H)
  year: 2024 - present

- role: Reviewer
  link: 
  organization: International Conference on Artificial Intelligence and Statistics (AISTATS)
  year: 2024

- role: Secretary
  link: https://cseg-michigan.github.io/
  organization: CSE Graduate Student Organization, University of Michigan
  year: 2024 - present